# Reto: Deserción de empleados

1. Importar librerias requeridasd

In [19]:
# Importar librerias que vamos a utilizar
from google.colab import files
import pandas as pd
import numpy as np
#por que el pandas me pone True o False
from numpy._core.numeric import astype

2. Lee el archivo CSV llamado empleadosRETO.csv y coloca los datos en un frame de Pandas llamado EmpleadosAttrition.

In [2]:
uploaded = files.upload()

Saving 0.mikh5r1gs60.fukzkek4yb4empleadosRETO.csv to 0.mikh5r1gs60.fukzkek4yb4empleadosRETO.csv

In [3]:
df_empleadosReto = pd.read_csv('0.mikh5r1gs60.fukzkek4yb4empleadosRETO.csv')

pd.set_option('display.max_columns', None)
df_empleadosReto.head()

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,HiringDate,Over18,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,StandardHours,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,1,997,4,Male,3,4,Research Director,4,Divorced,17399,9,06/06/2013,Y,No,22,4,3,80,32,1,2,4,1,No
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,1,178,2,Male,3,2,Manufacturing Director,2,Divorced,4941,6,12/25/2015,Y,No,20,4,4,80,7,0,3,2,0,No
2,21,Travel_Rarely,Sales,7 km,1,Marketing,1,1780,2,Male,3,1,Sales Representative,2,Single,2679,1,2/14/2017,Y,No,13,3,2,80,1,3,3,0,1,Yes
3,52,Travel_Rarely,Research & Development,7 km,4,Life Sciences,1,1118,2,Male,3,3,Healthcare Representative,2,Single,10445,7,7/29/2010,Y,No,19,3,4,80,18,4,3,6,4,No
4,33,Travel_Rarely,Research & Development,15 km,1,Medical,1,582,2,Male,3,3,Manager,3,Married,13610,7,10/07/2011,Y,Yes,12,3,4,80,15,2,4,6,7,Yes

In [4]:
df_empleadosReto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 30 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       400 non-null    int64
 1   BusinessTravel            396 non-null    object
 2   Department                400 non-null    object
 3   DistanceFromHome          400 non-null    object
 4   Education                 400 non-null    int64
 5   EducationField            400 non-null    object
 6   EmployeeCount             400 non-null    int64
 7   EmployeeNumber            400 non-null    int64
 8   EnvironmentSatisfaction   400 non-null    int64
 9   Gender                    400 non-null    object
 10  JobInvolvement            400 non-null    int64
 11  JobLevel                  400 non-null    int64
 12  JobRole                   400 non-null    object
 13  JobSatisfaction           400 non-null    int64
 14  MaritalStatus             395 non-null    object
 15  MonthlyIncome             400 non-null    int64
 16  NumCompaniesWorked        400 non-null    int64
 17  HiringDate                400 non-null    object
 18  Over18                    400 non-null    object
 19  OverTime                  400 non-null    object
 20  PercentSalaryHike         400 non-null    int64
 21  PerformanceRating         400 non-null    int64
 22  RelationshipSatisfaction  400 non-null    int64
 23  StandardHours             400 non-null    int64
 24  TotalWorkingYears         400 non-null    int64
 25  TrainingTimesLastYear     400 non-null    int64
 26  WorkLifeBalance           400 non-null    int64
 27  YearsInCurrentRole        400 non-null    int64
 28  YearsSinceLastPromotion   400 non-null    int64
 29  Attrition                 400 non-null    object
dtypes: int64(19), object(11)
memory usage: 93.9+ KB

3. Elimina las columnas que, con alta probabilidad (estimada por ti), no tienen relación alguna con la salida. Hay algunas columnas que contienen información que no ayuda a definir el desgaste de un empleado, tal es caso de las siguientes:
* EmployeeCount: número de empleados, todos tienen un 1
* EmployeeNumber: ID del empleado, el cual es único para cada empleado
* Over18: mayores de edad, todos dicen “Y”
* StandardHours: horas de trabajo, todos tienen “80”

In [5]:
df_empleadosReto.columns

Index(['Age', 'BusinessTravel', 'Department', 'DistanceFromHome', 'Education',
       'EducationField', 'EmployeeCount', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'JobInvolvement', 'JobLevel',
       'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'HiringDate', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'Attrition'],
      dtype='object')

In [29]:
df_empleados1 = df_empleadosReto.drop(['EmployeeCount', 'EmployeeNumber', 'Over18', 'StandardHours'], axis=1)
df_empleados1.head()

,Age,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,HiringDate,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,Research Director,4,Divorced,17399,9,06/06/2013,No,22,4,3,32,1,2,4,1,No
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,Manufacturing Director,2,Divorced,4941,6,12/25/2015,No,20,4,4,7,0,3,2,0,No
2,21,Travel_Rarely,Sales,7 km,1,Marketing,2,Male,3,1,Sales Representative,2,Single,2679,1,2/14/2017,No,13,3,2,1,3,3,0,1,Yes
3,52,Travel_Rarely,Research & Development,7 km,4,Life Sciences,2,Male,3,3,Healthcare Representative,2,Single,10445,7,7/29/2010,No,19,3,4,18,4,3,6,4,No
4,33,Travel_Rarely,Research & Development,15 km,1,Medical,2,Male,3,3,Manager,3,Married,13610,7,10/07/2011,Yes,12,3,4,15,2,4,6,7,Yes


4. Analizando la información proporcionada, detectaste que no se cuenta con los años que el empelado lleva en la compañía y parece ser un buen dato. Dicha cantidad se puede calcular con la fecha de contratación 'HiringDate':

  a. Crea una columna llamada Year y obtén el año de contratación del empleado a partir de su fecha 'HiringDate'. No se te olvide que debe ser un entero.

  b. Crea una columna llamada YearsAtCompany que contenga los años que el empleado lleva en la compañía hasta el año 2018. Para su cálculo, usa la variable Year que acabas de crear.

In [7]:
type(df_empleados1['HiringDate'][0])

str

In [30]:
df_empleados1['Year'] = pd.to_datetime(df_empleados1['HiringDate'], errors='coerce').dt.year.fillna(0).astype(int)
df_empleados1['Year'].value_counts()

Year
2013    52
2017    46
2014    34
2008    31
2015    29
2016    24
2010    23
2011    22
2009    22
2012    20
2018    17
2007    10
1998     9
2005     9
1996     8
2003     8
2006     6
1997     5
2004     4
2000     4
1999     3
2001     3
2002     3
1994     2
1993     1
1985     1
0        1
1991     1
1989     1
1992     1
Name: count, dtype: int64

In [31]:
#tenemos una observación con año igual a 0, lo que abra de corregir el dato no es nececario eliminarlo por el momento

df_empleados1['YearsAtCompany'] = 2018 - df_empleados1['Year']
df_empleados1['YearsAtCompany'].value_counts()

YearsAtCompany
5       52
1       46
4       34
10      31
3       29
2       24
8       23
7       22
9       22
6       20
0       17
11      10
20       9
13       9
22       8
15       8
12       6
21       5
14       4
18       4
19       3
17       3
16       3
24       2
25       1
33       1
2018     1
27       1
29       1
26       1
Name: count, dtype: int64

5. La DistanceFromHome está dada en kilómetros, pero tiene las letras “km” al final y así no puede ser entera:

a. Renombra la variable DistanceFromHome a DistanceFromHome_km.

b. Crea una nueva variable DistanceFromHome que sea entera, es decir, solo con números.

In [32]:
df_empleados1.rename(columns={'DistanceFromHome': 'DistanceFromHome_km'}, inplace=True)
df_empleados1.head()

,Age,BusinessTravel,Department,DistanceFromHome_km,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,HiringDate,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,Year,YearsAtCompany
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,Research Director,4,Divorced,17399,9,06/06/2013,No,22,4,3,32,1,2,4,1,No,2013,5
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,Manufacturing Director,2,Divorced,4941,6,12/25/2015,No,20,4,4,7,0,3,2,0,No,2015,3
2,21,Travel_Rarely,Sales,7 km,1,Marketing,2,Male,3,1,Sales Representative,2,Single,2679,1,2/14/2017,No,13,3,2,1,3,3,0,1,Yes,2017,1
3,52,Travel_Rarely,Research & Development,7 km,4,Life Sciences,2,Male,3,3,Healthcare Representative,2,Single,10445,7,7/29/2010,No,19,3,4,18,4,3,6,4,No,2010,8
4,33,Travel_Rarely,Research & Development,15 km,1,Medical,2,Male,3,3,Manager,3,Married,13610,7,10/07/2011,Yes,12,3,4,15,2,4,6,7,Yes,2011,7

In [33]:
df_empleados1['DistanceFromHome'] = df_empleados1['DistanceFromHome_km'].str.replace('km', '').astype(int)
df_empleados1.head()

,Age,BusinessTravel,Department,DistanceFromHome_km,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,HiringDate,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,Year,YearsAtCompany,DistanceFromHome
0,50,Travel_Rarely,Research & Development,1 km,2,Medical,4,Male,3,4,Research Director,4,Divorced,17399,9,06/06/2013,No,22,4,3,32,1,2,4,1,No,2013,5,1
1,36,Travel_Rarely,Research & Development,6 km,2,Medical,2,Male,3,2,Manufacturing Director,2,Divorced,4941,6,12/25/2015,No,20,4,4,7,0,3,2,0,No,2015,3,6
2,21,Travel_Rarely,Sales,7 km,1,Marketing,2,Male,3,1,Sales Representative,2,Single,2679,1,2/14/2017,No,13,3,2,1,3,3,0,1,Yes,2017,1,7
3,52,Travel_Rarely,Research & Development,7 km,4,Life Sciences,2,Male,3,3,Healthcare Representative,2,Single,10445,7,7/29/2010,No,19,3,4,18,4,3,6,4,No,2010,8,7
4,33,Travel_Rarely,Research & Development,15 km,1,Medical,2,Male,3,3,Manager,3,Married,13610,7,10/07/2011,Yes,12,3,4,15,2,4,6,7,Yes,2011,7,15

6. Borra las columnas Year, HiringDate y DistanceFromHome_km debido a que ya no son útiles.

In [34]:
df_empleados1.drop(['Year', 'HiringDate', 'DistanceFromHome_km'], axis=1, inplace=True)
df_empleados1.head()

,Age,BusinessTravel,Department,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,MonthlyIncome,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,YearsAtCompany,DistanceFromHome
0,50,Travel_Rarely,Research & Development,2,Medical,4,Male,3,4,Research Director,4,Divorced,17399,9,No,22,4,3,32,1,2,4,1,No,5,1
1,36,Travel_Rarely,Research & Development,2,Medical,2,Male,3,2,Manufacturing Director,2,Divorced,4941,6,No,20,4,4,7,0,3,2,0,No,3,6
2,21,Travel_Rarely,Sales,1,Marketing,2,Male,3,1,Sales Representative,2,Single,2679,1,No,13,3,2,1,3,3,0,1,Yes,1,7
3,52,Travel_Rarely,Research & Development,4,Life Sciences,2,Male,3,3,Healthcare Representative,2,Single,10445,7,No,19,3,4,18,4,3,6,4,No,8,7
4,33,Travel_Rarely,Research & Development,1,Medical,2,Male,3,3,Manager,3,Married,13610,7,Yes,12,3,4,15,2,4,6,7,Yes,7,15

7. Aprovechando los ajustes que se están haciendo, la empresa desea saber si todos los departamentos tienen un ingreso promedio similar. Genera una nuevo frame llamado SueldoPromedioDepto que contenga el MonthlyIncome promedio por departamento de los empleados y colócalo en una variable llamada SueldoPromedio. Esta tabla solo es informativa, no la vas a utilizar en el set de datos que estás construyendo.

In [35]:
SueldoPromedioDepto = df_empleados1.groupby(['Department'])[['MonthlyIncome']].agg('mean').reset_index()
SueldoPromedioDepto

               Department  MonthlyIncome
0         Human Resources    6239.888889
1  Research & Development    6804.149813
2                   Sales    7188.250000

8. La variable MonthlyIncome tiene un valor numérico muy grande comparada con las otras variables. Escala dicha variable para que tenga un valor entre 0 y 1.

In [36]:
#importamos primero libreria

from sklearn import preprocessing

escalador = preprocessing.MinMaxScaler()

# Aquí aplicare distinto a lo que nos enseñaron en el curso(lo que dice en el pdf y material no venía algo similar) por que el dataframe tambien trae strings
df_empleados1['MonthlyIncome_norm'] = escalador.fit_transform(df_empleados1[['MonthlyIncome']])

df_empleados1.drop(['MonthlyIncome'], axis=1, inplace=True)
df_empleados1.head()

,Age,BusinessTravel,Department,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,YearsAtCompany,DistanceFromHome,MonthlyIncome_norm
0,50,Travel_Rarely,Research & Development,2,Medical,4,Male,3,4,Research Director,4,Divorced,9,No,22,4,3,32,1,2,4,1,No,5,1,0.864269
1,36,Travel_Rarely,Research & Development,2,Medical,2,Male,3,2,Manufacturing Director,2,Divorced,6,No,20,4,4,7,0,3,2,0,No,3,6,0.207340
2,21,Travel_Rarely,Sales,1,Marketing,2,Male,3,1,Sales Representative,2,Single,1,No,13,3,2,1,3,3,0,1,Yes,1,7,0.088062
3,52,Travel_Rarely,Research & Development,4,Life Sciences,2,Male,3,3,Healthcare Representative,2,Single,7,No,19,3,4,18,4,3,6,4,No,8,7,0.497574
4,33,Travel_Rarely,Research & Development,1,Medical,2,Male,3,3,Manager,3,Married,7,Yes,12,3,4,15,2,4,6,7,Yes,7,15,0.664470

9. Todo parece indicar que las variables categóricas que quedan sí son importantes para obtener la variable de salida. Convierte todas las variables categóricas que quedan a numéricas:

a. BusinessTravel

b. Department

c. EducationField

d. Gender

e. JobRole

f. MaritalStatus

j. Attrition

In [37]:
# One-hot encoding

BusinessTravel_OH = pd.get_dummies(df_empleados1['BusinessTravel'], prefix = 'BusinessTravel').astype(int)
Department_OH = pd.get_dummies(df_empleados1['Department'], prefix = 'Department').astype(int)
EducationField_OH = pd.get_dummies(df_empleados1['EducationField'], prefix = 'EducationField').astype(int)
Gender_OH = pd.get_dummies(df_empleados1['Gender'], prefix = 'Gender').astype(int)
JobRole_OH = pd.get_dummies(df_empleados1['JobRole'], prefix = 'JobRole').astype(int)
MaritalStatus_OH = pd.get_dummies(df_empleados1['MaritalStatus'], prefix = 'MaritalStatus').astype(int)
Attrition_OH = pd.get_dummies(df_empleados1['Attrition'], prefix = 'Attrition').astype(int)

In [38]:
# Unir las nuevas bases

df_empleados2 = pd.concat([df_empleados1, BusinessTravel_OH, Department_OH, EducationField_OH, Gender_OH, JobRole_OH, MaritalStatus_OH, Attrition_OH], axis=1)
df_empleados2.head()

,Age,BusinessTravel,Department,Education,EducationField,EnvironmentSatisfaction,Gender,JobInvolvement,JobLevel,JobRole,JobSatisfaction,MaritalStatus,NumCompaniesWorked,OverTime,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,Attrition,YearsAtCompany,DistanceFromHome,MonthlyIncome_norm,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,Gender_Female,Gender_Male,JobRole_Healthcare Representative,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Attrition_No,Attrition_Yes
0,50,Travel_Rarely,Research & Development,2,Medical,4,Male,3,4,Research Director,4,Divorced,9,No,22,4,3,32,1,2,4,1,No,5,1,0.864269,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0
1,36,Travel_Rarely,Research & Development,2,Medical,2,Male,3,2,Manufacturing Director,2,Divorced,6,No,20,4,4,7,0,3,2,0,No,3,6,0.207340,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0
2,21,Travel_Rarely,Sales,1,Marketing,2,Male,3,1,Sales Representative,2,Single,1,No,13,3,2,1,3,3,0,1,Yes,1,7,0.088062,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,1
3,52,Travel_Rarely,Research & Development,4,Life Sciences,2,Male,3,3,Healthcare Representative,2,Single,7,No,19,3,4,18,4,3,6,4,No,8,7,0.497574,0,0,1,0,1,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0
4,33,Travel_Rarely,Research & Development,1,Medical,2,Male,3,3,Manager,3,Married,7,Yes,12,3,4,15,2,4,6,7,Yes,7,15,0.664470,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1

10. Ahora debes hacer la evaluación de las variables para quedarte con las mejores. Calcula la correlación lineal de cada una de las variables con respecto al Attrition.

In [39]:
df_empleados2.columns

Index(['Age', 'BusinessTravel', 'Department', 'Education', 'EducationField',
       'EnvironmentSatisfaction', 'Gender', 'JobInvolvement', 'JobLevel',
       'JobRole', 'JobSatisfaction', 'MaritalStatus', 'NumCompaniesWorked',
       'OverTime', 'PercentSalaryHike', 'PerformanceRating',
       'RelationshipSatisfaction', 'TotalWorkingYears',
       'TrainingTimesLastYear', 'WorkLifeBalance', 'YearsInCurrentRole',
       'YearsSinceLastPromotion', 'Attrition', 'YearsAtCompany',
       'DistanceFromHome', 'MonthlyIncome_norm', 'BusinessTravel_Non-Travel',
       'BusinessTravel_Travel_Frequently', 'BusinessTravel_Travel_Rarely',
       'Department_Human Resources', 'Department_Research & Development',
       'Department_Sales', 'EducationField_Human Resources',
       'EducationField_Life Sciences', 'EducationField_Marketing',
       'EducationField_Medical', 'EducationField_Other',
       'EducationField_Technical Degree', 'Gender_Female', 'Gender_Male',
       'JobRole_Healthcare Representative', 'JobRole_Human Resources',
       'JobRole_Laboratory Technician', 'JobRole_Manager',
       'JobRole_Manufacturing Director', 'JobRole_Research Director',
       'JobRole_Research Scientist', 'JobRole_Sales Executive',
       'JobRole_Sales Representative', 'MaritalStatus_Divorced',
       'MaritalStatus_Married', 'MaritalStatus_Single', 'Attrition_No',
       'Attrition_Yes'],
      dtype='object')

In [40]:
#Eliminó aquí la obs que trae "2018 años trabajando" para evitar sesgos al análisis
df_empleados2 = df_empleados2[df_empleados2['YearsAtCompany'] != 2018]

#Elimino las 7 variables que hice dummies y ademas me quedo con una de attrition dummy y OverTime que no la habia eliminado anteriormente
#a. BusinessTravel
#b. Department
#c. EducationField
#d. Gender
#e. JobRole
#f. MaritalStatus
#j. Attrition

df_empleados2 = df_empleados2.drop(['BusinessTravel', 'Department', 'EducationField',
       'Gender', 'JobRole', 'MaritalStatus', 'Attrition', 'Attrition_No', 'OverTime'], axis=1)
df_empleados2.head()

,Age,Education,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,YearsAtCompany,DistanceFromHome,MonthlyIncome_norm,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,Gender_Female,Gender_Male,JobRole_Healthcare Representative,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Attrition_Yes
0,50,2,4,3,4,4,9,22,4,3,32,1,2,4,1,5,1,0.864269,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0
1,36,2,2,3,2,2,6,20,4,4,7,0,3,2,0,3,6,0.207340,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0
2,21,1,2,3,1,2,1,13,3,2,1,3,3,0,1,1,7,0.088062,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,1,1
3,52,4,2,3,3,2,7,19,3,4,18,4,3,6,4,8,7,0.497574,0,0,1,0,1,0,0,1,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,1,0
4,33,1,2,3,3,3,7,12,3,4,15,2,4,6,7,7,15,0.664470,0,0,1,0,1,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1

11. Selecciona solo aquellas variables que tengan una correlación mayor o igual a 0.1, dejándolas en otro frame llamado EmpleadosAttritionFinal. No olvides mantener la variable de salida Attrition; esto es equivalente a borrar las que no cumplen con el límite.

In [45]:
#obtener correlación
df_empleados3 = df_empleados2.corr()

df_empleados3

,Age,Education,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,NumCompaniesWorked,PercentSalaryHike,PerformanceRating,RelationshipSatisfaction,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsInCurrentRole,YearsSinceLastPromotion,YearsAtCompany,DistanceFromHome,MonthlyIncome_norm,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,EducationField_Marketing,EducationField_Medical,EducationField_Other,EducationField_Technical Degree,Gender_Female,Gender_Male,JobRole_Healthcare Representative,JobRole_Human Resources,JobRole_Laboratory Technician,JobRole_Manager,JobRole_Manufacturing Director,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Attrition_Yes
Age,1.000000,0.200703,-0.006543,0.038132,0.458282,0.002529,0.328383,0.003189,0.008038,0.088471,0.628216,-0.078635,0.013184,0.130284,0.118777,0.185907,0.014237,0.441070,-0.067135,-0.014108,0.062199,0.009474,0.085048,-0.089703,0.000344,-0.044740,0.039006,0.069386,-0.017847,-0.078518,-0.009972,0.009972,0.122102,-0.032578,-0.117141,0.235145,0.051220,0.196375,-0.124422,-0.033694,-0.236099,-0.003714,0.090293,-0.109393,-0.212459
Education,0.200703,1.000000,-0.014185,0.002132,0.007115,-0.031632,0.092049,-0.005107,-0.041229,0.078327,0.068459,-0.033961,0.027169,0.052528,0.041604,0.045575,0.034480,0.000632,-0.014160,-0.029370,0.053399,0.011880,0.000417,-0.004244,0.028501,0.014524,0.082193,-0.116260,0.073127,0.018892,-0.048504,0.048504,0.089229,-0.005720,-0.015588,-0.075369,-0.042674,0.008085,0.029842,0.075415,-0.136240,0.055107,-0.045276,0.011531,-0.054478
EnvironmentSatisfaction,-0.006543,-0.014185,1.000000,0.017086,-0.055989,-0.003375,0.023802,-0.041344,0.001429,-0.037987,-0.034814,-0.004754,-0.012742,-0.011526,-0.010147,-0.013874,-0.085390,-0.049108,-0.018111,-0.037753,0.028684,-0.001367,0.058917,-0.059591,-0.012625,0.008320,-0.039068,0.022359,0.075450,-0.077732,-0.035010,0.035010,-0.037957,-0.006636,0.022036,0.040157,0.004244,-0.049942,0.116108,-0.063283,-0.045643,0.010723,0.011083,-0.015626,-0.125091
JobInvolvement,0.038132,0.002132,0.017086,1.000000,-0.017083,-0.025471,-0.027654,-0.066809,-0.091614,0.011585,-0.030933,0.003091,0.010831,-0.026505,-0.034140,-0.010812,0.068870,-0.030251,-0.112244,0.019356,0.052766,-0.004141,-0.002559,0.003939,-0.020947,-0.027246,0.006949,0.067740,-0.032764,-0.046397,-0.064659,0.064659,0.006028,0.012307,0.018141,-0.011799,-0.064868,0.015202,0.035208,-0.011409,-0.002361,-0.047232,0.106417,-0.062550,-0.168047
JobLevel,0.458282,0.007115,-0.055989,-0.017083,1.000000,0.016961,0.166491,0.005878,0.010167,0.035425,0.753525,-0.018904,0.085302,0.396213,0.384199,0.507785,0.019508,0.951705,0.019866,0.029065,-0.020628,-0.022010,-0.063939,0.072225,-0.002383,-0.029757,0.030528,0.044989,-0.032398,-0.035001,0.070573,-0.070573,0.085231,-0.068432,-0.363254,0.476534,0.102833,0.498984,-0.395030,0.087937,-0.239814,-0.018977,0.051532,-0.055129,-0.214486
JobSatisfaction,0.002529,-0.031632,-0.003375,-0.025471,0.016961,1.000000,-0.019904,-0.034717,-0.041260,0.011545,-0.005135,-0.021478,-0.035150,0.065944,-0.011529,0.038013,-0.007494,-0.006303,0.059675,-0.006659,-0.028959,-0.015444,-0.012722,0.017929,-0.028769,0.009953,-0.036798,0.012722,-0.049645,0.061685,-0.088214,0.088214,0.016675,-0.037652,-0.035005,-0.003621,0.050383,-0.063326,0.030413,0.055430,-0.071526,0.066942,-0.041055,-0.011401,-0.163964
NumCompaniesWorked,0.328383,0.092049,0.023802,-0.027654,0.166491,-0.019904,1.000000,0.013303,0.020118,0.051608,0.251986,-0.075428,-0.004181,-0.057459,-0.050021,-0.105491,0.079077,0.173504,0.037165,-0.130371,0.091401,0.087726,0.053429,-0.082647,0.097220,-0.033345,0.009920,0.040983,0.007063,-0.086833,0.062612,-0.062612,0.083200,0.049738,-0.013469,0.097804,0.024378,0.102613,-0.116020,-0.033052,-0.124966,0.015593,0.013530,-0.035810,-0.008590
PercentSalaryHike,0.003189,-0.005107,-0.041344,-0.066809,0.005878,-0.034717,0.013303,1.000000,0.787836,-0.063641,0.065619,-0.006687,-0.003090,0.078678,0.078239,0.068593,0.012990,0.006253,0.044979,0.021773,-0.048233,0.022473,0.010316,-0.017737,0.027045,0.072476,0.001183,-0.024372,-0.101159,-0.030589,-0.028343,0.028343,0.020995,-0.001384,-0.030665,0.069129,0.030626,-0.031902,0.030752,-0.066617,0.014898,-0.051864,0.036144,0.000821,-0.061714
PerformanceRating,0.008038,-0.041229,0.001429,-0.091614,0.010167,-0.041260,0.020118,0.787836,1.000000,-0.027159,0.060414,-0.043013,-0.031489,0.087976,0.108027,0.065007,-0.005607,0.008634,0.036057,-0.028158,-0.001760,-0.029885,0.024705,-0.015563,-0.015430,0.061687,0.023114,-0.038340,-0.077460,-0.003804,-0.007522,0.007522,-0.011081,-0.068820,0.024130,0.080905,0.023103,-0.039562,0.031070,-0.062316,0.007961,-0.045700,-0.040499,0.073516,-0.007010
RelationshipSatisfaction,0.088471,0.078327,-0.037987,0.011585,0.035425,0.011545,0.051608,-0.063641,-0.027159,1.000000,0.017142,-0.013124,0.053143,-0.039063,0.050991,0.001687,0.027300,0.050395,0.058874,0.011535,-0.048578,0.041415,-0.026140,0.013317,0.071332,-0.017108,0.055566,-0.003075,-0.089649,0.015672,-0.069114,0.069114,-0.046304,0.022652,-0.012366,0.053414,0.056185,-0.026093,-0.048928,0.057916,-0.052409,0.046262,0.003544,-0.025025,-0.032777
TotalWorkingYears,0.628216,0.068459,-0.034814,-0.030933,0.753525,-0.005135,0.251986,0.065619,0.060414,0.017142,1.000000,-0.056853,0.008367,0.429376,0.386666,0.555365,0.060883,0.740149,-0.043106,0.014434,0.030367,0.000360,0.058540,-0.059763,-0.006520,-0.053119,0.008432,0.078812,-0.002673,-0.051021,0.083393,-0.083393,0.103599,-0.040899,-0.225807,0.400078,0.069603,0.359396,-0.230652,-0.044890,-0.239093,-0.006730,0.083311,-0.086021,-0.214043
TrainingTimesLastYear,-0.078635,-0.033961,-0.004754,0.003091,-0.018904,-0.021478,-0.075428,-0.006687,-0.043013,-0.013124,-0.056853,1.000000,0.085389,-0.013373,-0.005435,-0.002406,-0.036770,-0.030639,-0.052043,0.025416,-0.021891,-0.012021,-0.075626,0.080922,-0.020375,-0.069888,0.003536,0.042810,-0.059989,0.127455,0.069337,-0.069337,-0.049978,-0.015909,0.033297,-0.000039,0.029459,-0.051867,-0.065257,0.049962,0.061837,0.032218,0.004323,-0.014670,-0.071592
WorkLifeBalance,0.013184,0.027169,-0.012742,0.010831,0.085302,-0.035150,-0.004181,-0.003090,-0.031489,0.053143,0.008367,0.085389,1.000000,0.069930,0.004058,0.032430,-0.015514,0.089460,0.072186,0.006798,-0.051100,0.000190,-0.011541,0.011698,0.016084,-0.025703,-0.035621,-0.028431,0.021868,0.130306,-0.034483,0.034483,-0.038545,-0.005784,-0.060931,0.057903,0.065797,0.052909,-0.053264,-0.000368,0.024468,0.012438,-0.032323,0.039950,-0.023063
YearsInCurrentRole,0.130284,0.052528,-0.011526,-0.026505,0.396213,0.065944,-0.057459,0.078678,0.087976,-0.039063,0.429376,-0.013373,0.069930,1.000000,0.589855,0.792957,-0.009093,0.373811,0.002585,-0.002825,0.009414,-0.060631,-0.037823,0.058034,-0.033135,-0.048714,0.030116,0.013868,0.004151,0.054629,0.063820,-0.063820,0.012471,-0.052361,-0.122540,0.139071,0.012166,0.221421,-0.147496,0.104852,-0.160642,0.043674,0.056943,-0.124982,-0.204453
YearsSinceLastPromotion,0.118777,0.041604,-0.010147,-0.034140,0.384199,-0.011529,-0.050021,0.078239,0.108027,0.050991,0.386666,-0.005435,0.004058,0.589855,1.000000,0.691225,-0.003790,0.367437,-0.013535,-0.016990,0.032641,-0.014019,-0.053469,0.058988,-0.020411,-0.083752,0.019343,0.052020,-0.021346,0.082600,-0.007342,0.007342,0.064806,-0.012119,-0.114221,0.255287,-0.030171,0.073279,-0.140374,0.060420,-0.087323,0.004954,0.049216,-0.053739,-0.069835
YearsAtCompany,0.185907,0.045575,-0.013874,-0.010812,0.507785,0.038013,-0.105491,0.068593,0.065007,0.001687,0.555365,-0.002406,0.032430,0.792957,0.691225,1.000000,-0.032429,0.488440,-0.005582,-0.002533,0.016552,-0.054274,-0.009988,0.027629,-0.053397,-0.047386,0.020932,0.029511,-0.015405,0.061055,0.026261,-0.026261,0.008028,-0.044816,-0.120781,0.230671,0.035732,0.224136,-0.164554,0.054323,-0.176411,0.078593,0.037816,-0.127072,-0.176287
DistanceFromHome,0.014237,0.034480,-0.085390,0.068870,0.019508,-0.007494,0.079077,0.012990,-0.005607,0.027300,0.060883,-0.036770,-0.015514,-0.009093,-0.003790,-0.032429,1.000000,-0.004123,0.025889,-0.000737,-0.024189,-0.023720,0.049934,-0.043251,-0.003817,-0.038834,-0.015943,0.024830,0.043834,0.015117,0.076728,-0.076728,0.047098,-0.008988,-0.034663,-0.019027,-0.032330,0.025336,0.094333,-0.029022,-0.068353,0.006129,0.019911,-0.009489,0.052944
MonthlyIncome_norm,0.441070,0.000632,-0.049108,-0.030251,0.951705,-0.006303,0.173504,0.006253,0.008634,0.050395,0.740149,-0.030639,0.089460,0.373811,0.367437,0.488440,-0.004123,1.000000,0.012801,0.006407,0.001419,-0.020817,-0.031073,0.038354,0.002006,-0.033393,0.026490,0.059190,-0.039476,-0.047131,0.090765,-0.090765,0.031191,-0.065608,-0.339011,0.548236,0.035110,0.569761,-0.359319,0.017635,-0.220073,-0.026726,0.054543,-0.050632,-0.195044
BusinessTravel_Non-Travel,-0.067135,-0.014160,-0.018111,-0.112244,0.019866,0.059675,0.037165,0.044979,0.036057,0.058874,-0.043106,-0.052043,0.072186,0.002585,-0.013535,-0.005582,0.025889,0.012801,1.000000,-0.169967,-0.481686,0.063675,-0.037627,0.017864,0.084583,-0.013377,-0.076131,0.037627,0.045291,-0.042535,-0.058477,0.058477,-0.025565,0.013128,0.077919,0.049877,-0.002895,-0.015282,-0.107443,0.034870,-0.015448,0.071405,-0.089266,0.021666,-0.101103
BusinessTravel_Travel_Frequently,-0.014108,-0.029370,-0.037753,0.019356,0.029065,-0.006659,-0.130371,0.021773,-0.028158,0.011535,0.014434,0.025416,0.006798,-0.002825,-0.016990,-0.002533,-0.000737,0.006407,-0.169967,1.000000,-0.755731,-0.037044,-0.002751,0.014714,-0.022181,0.008445,0.004462,-0.036447,0.028868,0.036857,0.020315,-0.020315,0.073258,-0.030008,-0.067517,-0.061614,0.003163,-0.033880,0.036580,0.001580,0.069426,0.011354,-0.004539,0.008665,0.034833
BusinessTravel_Travel_Rarely,0.062199,0.053399,0.028684,0.052766,-0.020628,-0.028959,0.091401,-0.048233,-0.001760,-0.048578,0.030367,-0.021891,-0.051100,0.009414,0.032641,0.016552,-0.024189,0.001419,-0.481686,-0.755731,1.000000,-0.004904,0.022698,-0.021551,-0.031635,-0.000758,0.051511,0.011607,-0.049327,-0.023513,0.005162,-0.005162,-0.040634,0.020972,0.004690,0.027809,-0.011073,0.046172,0.032263,-0.012416,-0.067550,-0.055933,0.048749,-0.008035,0.043551
Department_Human Resources,0.009474,0.011880,-0.001367,-0.004141,-0.022010,-0.015444,0.087726,0.022473,-0.029885,0.041415,0.000360,-0.012021,0.000190,-0.060631,-0.014019,-0.054274,-0.023720,-0.020817,0.063675,-0.037044,-0.004904,1.000000,-0.216052,-0.101411,0.879664,-0.105233,-0.048566,-0.106812,0.045291,-0.036697,-0.026990,0.026990,-0.050707,0.941603,-0.068243,0.028281,-0.052105,-0.047840,-0.070071,-0.079038,-0.039276,0.072444,0.026449,-0.094309,0.023226
Department_Research & Development,0.085048,0.000417,0.058917,-0.002559,-0.063939,-0.012722,0.053429,0.010316,0.024705,-0.026140,0.058540,-0.075626,-0.011541,-0.037823,-0.053469,-0.009988,0.049934,-0.031073,-0.037627,-0.002751,0.022698,-0.216052,1.000000,-0.949438,-0.190053,0.087808,-0.454690,0.222676,0.082185,-0.040182,-0.026120,0.026120,0.234701,-0.203435,0.315864,-0.116510,0.241169,0.221426,0.324326,-0.739969,-0.367708,-0.002998,0.062601,-0.074629,-0.074053
Department_Sales,-0.089703,-0.004244,-0.059591,0.003939,0.072225,0.017929,-0.082647,-0.017737,-0.015563,0.013317,-0.059763,0.080922,0.011698,0.058034,0.058988,0.027629,-0.043251,0.038354,0.017864,0.014714,-0.021551,-0.101411,-0.949438,1.000000,-0.089208,-0.055631,0.478904,-0.192542,-0.098302,0.052742,0.035292,-0.035292,-0.222834,-0.095489,-0.299893,0.109619,-0.228975,-0.210231,-0.307928,0.779375,0.387290,-0.020239,-0.072290,0.106365,0.067985
EducationField_Human Resources,0.000344,0.028501,-0.012625,-0.020947,-0.002383,-0.028769,0.097220,0.027045,-0.015430,0.071332,-0.006520,-0.020375,0.016084,-0.033135,-0.020411,-0.053397,-0.003817,0.002006,0.084583,-0.022181,-0.031635,0.879664,-0.190053,-0.089208,1.000000,-0.122380,-0.042722,-0.093959,-0.029881,-0.032281,-0.036630,0.036630,-0.044606,0.798030,-0.060031,0.042066,-0.045835,-0.042083,-0.061639,-0.069527,-0.034549,0.014103,0.065772,-0.082960,0.043267
EducationField_Life Sciences,-0.044740,0.014524,0.008320,-0.027246,-0.029757,0.009953,-0.033345,0.072476,0.061687,-0.017108,-0.053119,-0.069888,-0.025703,-0.048714,-0.083752,-0.047386,-0.038834,-0.033393,-0.013377,0.008445,-0.000758,-0.105233,0.087808,-0.055631,-0.122380,1.000000,-0.292787,-0.643928,-0.204782,-0.221231,-0.006437,0.006437,-0.037624,-0.095099,0.073213,-0.078689,0.062997,0.045294,0.027388,-0.034066,-0.049905,-0.056382,-0.033258,0.071512,-0.028511
EducationField_Marketing,0.039006,0.082193,-0.039068,0.006949,0.030528,-0.036798,0.009920,0.001183,0.023114,0.055566,0.008432,0.003536,-0.035621,0.030116,0.019343,0.020932,-0.015943,0.026490,-0.076131,0.004462,0.051511,-0.048566,-0.454690,0.478904,-0.042722,-0.292787,1.000000,-0.224790,-0.071488,-0.077230,0.024870,-0.024870,-0.106716,-0.045730,-0.143620,0.055628,-0.109657,-0.100680,-0.147468,0.361236,0.202577,0.062619,-0.057848,-0.005654,0.020458
EducationField_Medical,0.069386,-0.116260,0.022359,0.067740,0.044989,0.012722,0.040983,-0.024372,-0.038340,-0.003075,0.078812,0.042810,-0.028431,0.013868,0.052020,0.029511,0.024830,0.059190,0.037627,-0.036447,0.011607,-0.106812,0.222676,-0.192542,-0.093959,-0.643928,-0.224790,1.000000,-0.157223,-0.169853,-0.049401,0.049401,0.102281,-0.100575,0.026143,0.094928,0.036541,0.020269,0.039804,-0.144668,-0.093869,0.040383,0.001445,-0.020467,-0.054974
EducationField_Other,-0.017847,0.073127,0.075450,-0.032764,-0.032398,-0.049645,0.007063,-0.101159,-0.077460,-0.089649,-0.002673,-0.059989,0.021868,0.004151,-0.021346,-0.015405,0.043834,-0.039476,0.045291,0.028868,-0.049327,0.045291,0.082185,-0.098302,-0.029881,-0.204782,-0.071488,-0.157223,1.000000,-0.054016,-0.023837,0.023837,0.003732,0.051975,0.056972,-0.059036,-0.038348,0.052813,0.051571,-0.058854,-0.057812,-0.015733,0.025830,-0.007504,-0.004525
EducationField_Technical Degree,-0.078518,0.018892,-0.077732,-0.046397,-0.035001,0.061685,-0.086833,-0.030589,-0.003804,0.015672,-0.051021,0.127455,0.130306,0.054629,0.082600,0.061055,0.015117,-0.047131,-0.042535,0.036857,-0.023513,-0.036697,-0.040182,0.052742,-0.032281,-0.221231,-0.077230,-0.169853,-0.054016,1.000000,0.127586,-0.127586,0.029047,-0.034554,-0.049769,-0.063778,-0.011299,-0.037749,0.032922,0.008401,0.118780,-0.033221,0.081178,-0.051955,0.128876
Gender_Female,-0.009972,-0.048504,-0.035010,-0.064659,0.070573,-0.088214,0.062612,-0.028343,-0.007522,-0.069114,0.083393,0.069337,-0.034483,0.063820,-0.007342,0.026261,0.076728,0.090765,-0.058477,0.020315,0.005162,-0.026990,-0.026120,0.035292,-0.036630,-0.006437,0.024870,-0.049401,-0.023837,0.127586,1.000000,-1.000000,-0.081841,-0.049556,-0.030019,0.042216,-0.011317,0.103509,-0.006322,0.015008,0.009922,-0.123756,0.053539,0.048293,0.030200
Gender_Male,0.009972,0.048504,0.035010,0.064659,-0.070573,0.088214,-0.062612,0.028343,0.007522,0.069114,-0.083393,-0.069337,0.034483,-0.063820,0.007342,-0.026261,-0.076728,-0.090765,0.058477,-0.020315,-0.005162,0.026990,0.026120,-0.035292,0.036630,0.006437,-0.024870,0.049401,0.023837,-0.127586,-1.000000,1.000000,0.081841,0.049556,0.030019,-0.042216,0.011317,-0.103509,0.006322,-0.015008,-0.009922,0.123756,-0.053539,-0.048293,-0.030200
JobRole_Healthcare Representative,0.122102,0.089229,-0.037957,0.006028,0.085231,0.016675,0.083200,0.020995,-0.011081,-0.046304,0.103599,-0.049978,-0.038545,0.012471,0.064806,0.008028,0.047098,0.031191,-0.025565,0.073258,-0.040634,-0.050707,0.234701,-0.222834,-0.044606,-0.037624,-0.106716,0.102281,0.003732,0.029047,-0.081841,0.081841,1.000000,-0.047746,-0.149952,-0.088128,-0.114492,-0.105119,-0.153969,-0.173671,-0.086301,0.007339,0.020956,-0.039625,-0.103686
JobRole_Human Resources,-0.032578,-0.005720,-0.006636,0.012307,-0.068432,-0.037652,0.049738,-0.001384,-0.068820,0.022652,-0.040899,-0.015909,-0.005784,-0.052361,-0.012119,-0.044816,-0.008988,-0.065608,0.013128,-0.030008,0.020972,0.941603,-0.203435,-0.095489,0.798030,-0.095099,-0.045730,-0.100575,0.051975,-0.034554,-0.049556,0.049556,-0.047746,1.000000,-0.064258,-0.037765,-0.049062,-0.045046,-0.065979,-0.074422,-0.036982,0.086804,0.008980,-0.088802,0.032564
JobRole_Laboratory Technician,-0.117141,-0.015588,0.022036,0.018141,-0.363254,-0.035005,-0.013469,-0.030665,0.024130,-0.012366,-0.225807,0.033297,-0.060931,-0.122540,-0.114221,-0.120781,-0.034663,-0.339011,0.077919,-0.067517,0.004690,-0.068243,0.315864,-0.299893,-0.060031,0.073213,-0.143620,0.026143,0.056972,-0.049769,-0.030019,0.030019,-0.149952,-0.064258,1.000000,-0.118604,-0.154084,-0.141471,-0.207214,-0.233729,-0.116146,0.060857,-0.005388,-0.054451,0.124827
JobRole_Manager,0.235145,-0.075369,0.040157,-0.011799,0.476534,-0.003621,0.097804,0.069129,0.080905,0.053414,0.400078,-0.000039,0.057903,0.139071,0.255287,0.230671,-0.019027,0.548236,0.049877,-0.061614,0.027809,0.028281,-0.116510,0.109619,0.042066,-0.078689,0.055628,0.094928,-0.059036,-0.063778,0.042216,-0.042216,-0.088128,-0.037765,-0.118604,1.000000,-0.090557,-0.083144,-0.121782,-0.137365,-0.068260,-0.053585,0.057273,-0.005282,-0.090209
JobRole_Manufacturing Director,0.051220,-0.042674,0.004244,-0.064868,0.102833,0.050383,0.024378,0.030626,0.023103,0.056185,0.069603,0.029459,0.065797,0.012166,-0.030171,0.035732,-0.032330,0.035110,-0.002895,0.003163,-0.011073,-0.052105,0.241169,-0.228975,-0.045835,0.062997,-0.109657,0.036541,-0.038348,-0.011299,-0.011317,0.011317,-0.114492,-0.049062,-0.154084,-0.090557,1.000000,-0.108016,-0.158213,-0.178458,-0.088680,-0.021117,0.005168,0.023980,-0.042802
JobRole_Research Director,0.196375,0.008085,-0.049942,0.015202,0.498984,-0.063326,0.102613,-0.031902,-0.039562,-0.026093,0.359396,-0.051867,0.052909,0.221421,0.073279,0.224136,0.025336,0.569761,-0.015282,-0.033880,0.046172,-0.047840,0.221426,-0.210231,-0.042083,0.045294,-0.100680,0.020269,0.052813,-0.037749,0.103509,-0.103509,-0.105119,-0.045046,-0.141471,-0.083144,-0.108016,1.000000,-0.145261,-0.163849,-0.081420,-0.013541,0.019771,-0.019815,-0.116656
JobRole_Research Scientist,-0.124422,0.029842,0.116108,0.035208,-0.395030,0.030413,-0.116020,0.030752,0.031070,-0.048928,-0.230652,-0.065257,-0.053264,-0.147496,-0.140374,-0.164554,0.094333,-0.359319,-0.107443,0.036580,0.032263,-0.070071,0.324326,-0.307928,-0.061639,0.027388,-0.147468,0.039804,0.051571,0.032922,-0.006322,0.006322,-0.153969,-0.065979,-0.207214,-0.121782,-0.158213,-0.145261,1.000000,-0.239991,-0.119257,-0.012982,0.002548,0.007740,0.007467
JobRole_Sales Executive,-0.033694,0.075415,-0.063283,-0.011409,0.087937,0.055430,-0.033052,-0.066617,-0.062316,0.057916,-0.044890,0.049962,-0.000368,0.104852,0.060420,0.054323,-0.029022,0.017635,0.034870,0.001580,-0.012416,-0.079038,-0.739969,0.779375,-0.069527,-0.034066,0.361236,-0.144668,-0.058854,0.008401,0.015008,-0.015008,-0.173671,-0.074422,-0.233729,-0.137365,-0.178458,-0.163849,-0.239991,1.000000,-0.134518,0.022180,-0.022534,0.004827,-0.000991
JobRole_Sales Representative,-0.236099,-0.136240,-0.045643,-0.002361,-0.239814,-0.071526,-0.124966,0.014898,0.007961,-0.052409,-0.239093,0.061837,0.024468,-0.160642,-0.087323,-0.176411,-0.068353,-0.220073,-0.015448,0.069426,-0.067550,-0.039276,-0.367708,0.387290,-0.034549,-0.049905,0.202577,-0.093869,-0.057812,0.118780,0.009922,-0.009922,-0.086301,-0.036982,-0.116146,-0.068260,-0.088680,-0.081420,-0.119257,-0.134518,1.000000,-0.072946,-0.077028,0.162591,0.191070
MaritalStatus_Divorced,-0.003714,0.055107,0.010723,-0.047232,-0.018977,0.066942,0.015593,-0.051864,-0.045700,0.046262,-0.006730,0.032218,0.012438,0.043674,0.004954,0.078593,0.006129,-0.026726,0.071405,0.011354,-0.055933,0.072444,-0.002998,-0.020239,0.014103,-0.056382,0.062619,0.040383,-0.015733,-0.033221,-0.123756,0.123756,0.007339,0.086804,0.060857,-0.053585,-0.021117,-0.013541,-0.012982,0.022180,-0.072946,1.000000,-0.528649,-0.349446,-0.108565

In [48]:
#creo mejor un un df donde solo venga la correlación con respecto a attrition
df_empleados3_attrition = df_empleados2.corr()['Attrition_Yes'].abs()

Cumplen = df_empleados3_attrition[df_empleados3_attrition >= 0.1].index

EmpleadosAttritionFinal = df_empleados2[Cumplen]
EmpleadosAttritionFinal.head()

,Age,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,TotalWorkingYears,YearsInCurrentRole,YearsAtCompany,MonthlyIncome_norm,BusinessTravel_Non-Travel,EducationField_Technical Degree,JobRole_Healthcare Representative,JobRole_Laboratory Technician,JobRole_Research Director,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Single,Attrition_Yes
0,50,4,3,4,4,32,4,5,0.864269,0,0,0,0,1,0,1,0,0
1,36,2,3,2,2,7,2,3,0.207340,0,0,0,0,0,0,1,0,0
2,21,2,3,1,2,1,0,1,0.088062,0,0,0,0,0,1,0,1,1
3,52,2,3,3,2,18,6,8,0.497574,0,0,1,0,0,0,0,1,0
4,33,2,3,3,3,15,6,7,0.664470,0,0,0,0,0,0,0,0,1

12. Crea una nueva variable llamada EmpleadosAttritionPCA formada por los componentes principales del frame EmpleadosAttritionFinal. Recuerda que el resultado del proceso PCA es un numpy array, por lo que, para hacer referencia a una columna, por ejemplo, la 0, puedes usar la instrucción EmpleadosAttritionPCA[:,0]).

In [50]:
#Como no se escalaron anteriormente las características puede que salga raro (solo la de ingreso)
from sklearn.decomposition import PCA

pca = PCA(n_components=EmpleadosAttritionFinal.shape[1])

EmpleadosAttritionPCA = pca.fit_transform(EmpleadosAttritionFinal)

print(EmpleadosAttritionPCA[:,0])

[ 20.23990278  -6.39395882 -21.52677103  13.81615637  -1.4460947
  21.79388484 -18.22493437  -7.08029128   5.65365244 -11.0288198
  -4.00278368  16.92635081 -10.11868656   3.93637143  15.55386865
  -0.35697277  -6.77650372   3.89569908  11.9046977   20.94588733
  -4.94211629   4.73124105  -7.04932275 -20.45766335   4.90057008
  -1.18207279 -22.21215157 -10.992729    17.98092999   1.32964503
  -6.3091229   -0.86266449  20.922323    -4.17483631  -5.68554579
  12.65665576   1.61872687  25.05655219  -5.27590959  -0.69675181
  11.99615741  -5.02386372   5.80616016  -7.71553949  -4.65688035
  19.47341514  -3.41044641   6.05918537   3.53078207  -7.38913543
  -4.29371953  10.69306812  13.06493521  -9.4692553    0.54847668
 -12.11917316  -4.09536163  -7.77934056  12.32332025   2.27345855
   2.70844524  -4.12952499   4.86895129 -13.54426194   3.80033445
  -2.57829067  -0.51676317  -2.10528665   0.9143674   -4.86498352
   3.27664952  -5.19488774   0.58571406   0.66457227 -10.56271448
 -23.20891249 -10.04015111   4.13484986   3.7683661  -16.0327465
  -7.04131153  13.83377683  -3.81054718  -2.52107243 -20.83926491
  -9.55180914  14.03508278   6.29951465  -4.63244989   7.87553267
   0.81151001  -3.34397801   4.81323257  -3.71971745  -7.02916611
  -2.71732568  -6.8617658    3.79301043  -2.06907449  -4.01197316
  -6.60259556  -9.98260606  -5.77953736  -3.956775     2.49699239
  11.28946649  -0.7296389   -8.55339411  25.82816422 -12.8880453
 -15.34899934 -10.8995902   27.63316008   1.47980125  12.90507107
  11.30062813  -2.12565054  -0.73388934  15.19775271  15.66401565
  23.20752228  -4.70194481 -20.15515654   8.36203886  -6.56722383
  -5.22337789  -4.90645347  10.07733177  18.82143236  -4.80660328
  -5.66206152  11.26105641  -7.11085322  -0.77088471  -3.89925552
   8.74735678  11.68470892   7.46590166   1.25991181  27.75861925
   6.47987691  -1.59279427  16.89695919  32.46444434  -0.59687798
  23.12009211  -4.79088834   1.13865466 -19.32344378  -7.89133435
  -7.02613034  18.16325284   1.93382891   3.82383492   2.23210582
 -19.46067778  -8.49229768   2.20986604  -8.10614842  -5.21234196
  23.82688074   7.79175847   1.99407634  -9.30256217  -6.35268534
  -6.05891446  18.52343368 -12.66022855   2.23364527  24.69582209
  12.93553897  -5.76913682  12.04810622  15.54888264 -14.49724809
   0.76707899   5.14159003  15.25240393 -11.64158783  17.52286683
  -8.95186668  16.09173202  -3.26310906  -5.03917349  13.64534459
  -8.17924175  15.31936182 -22.88261565  -5.10990999   1.18390256
  -4.60498181   4.37252948  15.6040345   -6.45677555  13.76785324
  -2.63757423  -4.51071066  16.3418865   18.76289714  -6.47895739
   0.43743125  -7.31372761   0.8306086   -6.30763365 -12.47574844
 -10.50241583 -15.60637343   1.85839552   7.07789595  -6.77743899
  -5.55481     24.28902851  -2.10455564 -15.06410419 -15.34608523
  13.28158232   0.44297853   5.7749987    6.27281021 -16.02311072
   6.17606583 -11.06958817  14.47695252  12.63465213 -22.21643762
  -1.95802967  -1.05153483 -13.49754282   0.21457899  -8.45667451
  -4.473631    -1.10964058  14.08150705   3.78612672  -1.101039
  -1.80951788   7.05906997  -9.17290339   1.06363988  -9.00535829
   2.69171376 -10.99591626  -2.59647384  15.88620159  11.85511826
  29.14312288  12.92497987  -1.14226077  -4.3893513  -14.78636384
   5.02333299  -8.4326642   -6.70738218  16.65619435  10.01215312
 -20.9601512   -7.44072744  -8.04355901   4.56392808  19.00825036
 -12.98621312   2.44307212  26.03774374  -1.57974903  -0.24257749
   8.2907451  -20.1392552    8.61125063 -13.8185174   24.94313766
  13.34561234  -7.95282634  -9.39994803   5.46895858 -13.32174582
  -3.27294556  -0.17364046 -13.12454433   1.97407661  -2.10178793
  -1.21599236  -1.88741072   0.38590061  28.57806619  15.7553578
  -3.22846109 -10.37258828   6.66074761   6.27209367  -5.57622276
  -5.55110593 -14.48214355   8.6375042  -22.21290128   0.91377568
 -22.89975978 -12.75805041 -13.98572303  -2.94597491  -1.27326701
  13.98133676  23.0156433   10.99687299 -15.33965178  -2.04945498
   0.85154413 -17.68685731 -19.33397406   1.62467565  12.6935887
 -10.60540483  -0.91662186   2.85735435   2.27224175   5.189429
   0.11972057  -3.42435425   4.82793201   5.33282902  -5.14877671
  -5.16046552  15.68369773   0.79442171  -7.56992287  -8.4737587
  -5.46399701 -10.58990681  -2.74454509  11.45309851  -9.41989737
  -5.70795766 -12.5911227   -4.0144246  -14.77681001  12.4867111
   2.89531628  -2.41935643  -8.95882517  20.65764585  -3.92347821
  -0.64237282  -2.2632637   -1.35283516   6.55981222  -1.11485138
  13.12439941 -24.53228065  -7.40587103  -7.06010859 -11.44512066
  -2.79221028  27.28820455  -6.53967189  -4.45338866  -8.63069686
  -0.40863977   1.10116575  12.00747885   9.66928595  -6.57402725
  13.9403535    4.40811717 -15.20040588 -14.59727869   9.51513726
 -10.58545832   8.72162093  13.7621276   -5.79288299  11.37607573
  -1.15980521  -8.97745981  -8.78950783  -3.51544215   1.50628996
 -13.47955767 -12.22647285  16.42290038 -16.66436485  -0.75065217
  -7.38587203 -10.17808548   7.28826799  -7.66471566  -1.90214529
  -3.51939165  -2.4061989   -8.18030625   2.6056372   -4.78676131
  -9.93347057   6.46045362  13.57457529 -10.17816091  -6.98789519
 -12.05294883  -0.65319678  -6.32487954  -5.60230994]

13. Agrega el mínimo número de Componentes Principales en columnas del frame EmpleadosAttritionPCA que logren explicar el 80% de la varianza, al frame EmpleadosAttritionFinal. Puedes usar la instrucción assign, columna por columna, llamando a cada una C0, C1, etc., hasta las que vayas a agregar.

In [52]:
#Varianza acumulada de una mejor forma la pdf
var_acum = np.cumsum(pca.explained_variance_ratio_)

#Componentes que expliquen el 80%
componentes_80 = np.argmax(var_acum >= 0.8) + 1

print(componentes_80)

2

In [54]:
# Necesitamos dos componentes
nuevas_columnas = {f'C{i}': EmpleadosAttritionPCA[:, i] for i in range(componentes_80)}

EmpleadosAttritionFinal = EmpleadosAttritionFinal.assign(**nuevas_columnas)

EmpleadosAttritionFinal.head()

,Age,EnvironmentSatisfaction,JobInvolvement,JobLevel,JobSatisfaction,TotalWorkingYears,YearsInCurrentRole,YearsAtCompany,MonthlyIncome_norm,BusinessTravel_Non-Travel,EducationField_Technical Degree,JobRole_Healthcare Representative,JobRole_Laboratory Technician,JobRole_Research Director,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Single,Attrition_Yes,C0,C1
0,50,4,3,4,4,32,4,5,0.864269,0,0,0,0,1,0,1,0,0,20.239903,-4.207199
1,36,2,3,2,2,7,2,3,0.207340,0,0,0,0,0,0,1,0,0,-6.393959,-3.694290
2,21,2,3,1,2,1,0,1,0.088062,0,0,0,0,0,1,0,1,1,-21.526771,1.738866
3,52,2,3,3,2,18,6,8,0.497574,0,0,1,0,0,0,0,1,0,13.816156,-5.843657
4,33,2,3,3,3,15,6,7,0.664470,0,0,0,0,0,0,0,0,1,-1.446095,4.139927

14. Guarda el set de datos que has formado y que tienes en EmpleadosAttritionFinal en un archivo CSV llamado EmpleadosAttritionFinal.csv. Las últimas columnas que colocaste quedarán después de la variable Attrition, lo cual no importa, pero si gustas lo puedes arreglar antes de escribir el archivo.

In [55]:
EmpleadosAttritionFinal.to_csv('EmpleadosAttritionFinal.csv', index=False)

15. Descarga tu script (archivo con extensión .ipynb) y guárdalo en un archivo que siga la nomenclatura que se te indica en Formato de entrega de actividad.

16. Sube el archivo a Github.

17. Descarga el archivo de rúbrica y compara tus resultados con ella.

18. Publica tu archivo presionando el ícono ubicado en la parte inferior de la pantalla de Plataforma.

Formato de entrega de actividad:

Tu trabajo será evaluado con base en el cumplimiento de cada uno de los pasos indicados en las instrucciones, hasta llegar a tu archivo final. Como evidencia deberás entregar:
Tu programa en Pyhton en un archivo llamado RetoEmpleados.ipynb Jupyter notebook con todas las instrucciones necesarias para generar tu archivo final.
El mismo programa, pero en formato pdf, en un archivo llamado RetoEmpleados.pdf.
El archivo final obtenido (EmpleadosAttritionFinal.csv).